#  Template React Deploy

#  This template allows you to deploy your React app to an AWS S3 bucket and invalidate the old AWS Cloudfront distribution.
#  The workflow allows running tests, code linting and security scans on feature branches (as well as master).
#  The react app will be validated, deployed to S3 and trigger an AWS Cloudfront distribution invalidation to refresh the CDN caches after the code is merged to master.

# Prerequisites: $AWS_ACCESS_KEY_ID, $AWS_SECRET_ACCESS_KEY setup in the Deployment variables.
# For advanced cases, please, follow examples from the pipe's:
# README https://bitbucket.org/atlassian/aws-s3-deploy/src/master/README.md
# README https://bitbucket.org/atlassian/aws-cloudfront-invalidate/src/master/README.md

# NOTE: 배포를 위한 yml

image: node:16

# Workflow Configuration

pipelines:
  branches:
    develop:
      - step:
          name: dev build
          caches:
            - node
          script:
            - echo "start dev deploy ... "
            - ls -al

            - mkdir -p ~/.ssh
            - touch ~/.ssh/known_hosts
            - ssh-keyscan -H $DEV_SFTP_HOST >> ~/.ssh/known_hosts && chmod 600 ~/.ssh/known_hosts
            - cat ~/.ssh/known_hosts

            - apt-get update && apt-get install sshpass zip
            - npm i --legacy-peer-deps
            - npm run dev
            - cp ./.htaccess ./dist
            - cd ./dist
            - ls -al ./
            - zip -r channeltunadminfrontdev *
            - cd ..
            - mv ./dist/channeltunadminfrontdev.zip ./channeltunadminfrontdev.zip
            - ls -al ./

            - sshpass -p $DEV_SFTP_PASSWORD scp ./channeltunadminfrontdev.zip $DEV_SFTP_USER@$DEV_SFTP_HOST:/home/channeltune/deployZip/
            - sshpass -p $DEV_SFTP_PASSWORD ssh $DEV_SFTP_USER@$DEV_SFTP_HOST "sh /home/channeltune/deployDev.sh"
      - step:
          name: trigger swit build complete message
          script:
            - apt-get update && apt-get install -y unzip git
            - CMSG=`git log --format=%B -n 1 $BITBUCKET_COMMIT`
            - echo $CMSG
            - curl -X POST
              -H Content-Type:application/json
              --data "{\"text\":\"[DEV] channeltune admin front pipeline deploy - $CMSG\"}" https://hook.swit.io/chat/211208071815354ZiDp/KqtdEm7PeNOK9QkSuiDZ
          # artifacts:
          #   - dist/**
      # - step:
      #     name: deploy sftp server
      #     script:
      #       - pipe: atlassian/sftp-deploy:0.5.8
      #         variables:
      #           SERVER: $DEV_SFTP_HOST
      #           USER: $DEV_SFTP_USER
      #           PASSWORD: $DEV_SFTP_PASSWORD
      #           REMOTE_PATH: '/home/channeltune/deployDir/'
      #           LOCAL_PATH: 'dist/*'
      # - step:
      #     name: do deployDev bash
      #     script:
      #       - whoami
      #       - ls -al ./
    master:
      - step:
          name: prod build and deploy
          caches:
            - node
          script:
            - echo "start prod deploy ... "
            - apt-get update && apt-get install zip
            - npm i --legacy-peer-deps
            - npm run prod
            - cp ./appspec.yml ./dist/appspec.yml
            - cp -r ./bashScripts ./dist/bashScripts
            - ls -al ./dist
            - cd ./dist
            - zip -r channeltunadminfront *
            - cd ..
            - mv ./dist/channeltunadminfront.zip ./channeltunadminfront.zip
          artifacts:
            - channeltunadminfront.zip
          # artifacts:
          #   - deploy/**
      - step:
          name: upload to s3
          script:
            - pipe: atlassian/aws-code-deploy:1.1.1
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                COMMAND: "upload"
                APPLICATION_NAME: "channeltune_admin_front"
                S3_BUCKET: "tune.deploy.bucket"
                ZIP_FILE: "channeltunadminfront.zip"
                VERSION_LABEL: "channeltunadminfront.zip"
      - step:
          name: deploy to ec2
          script:
            - pipe: atlassian/aws-code-deploy:1.1.1
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                COMMAND: "deploy"
                APPLICATION_NAME: "channeltune_admin_front"
                DEPLOYMENT_GROUP: "channeltune_admin_front_group"
                S3_BUCKET: "tune.deploy.bucket"
                VERSION_LABEL: "channeltunadminfront.zip"
                IGNORE_APPLICATION_STOP_FAILURES: "true"
                WAIT: "true"
                FILE_EXISTS_BEHAVIOR: "OVERWRITE"
      - step:
          name: trigger swit build complete message
          script:
            - apt-get update && apt-get install -y unzip git
            - CMSG=`git log --format=%B -n 1 $BITBUCKET_COMMIT`
            - echo $CMSG
            - curl -X POST
              -H Content-Type:application/json
              --data "{\"text\":\"[PROD] channeltune admin front pipeline deploy - $CMSG\"}" https://hook.swit.io/chat/211208071815354ZiDp/KqtdEm7PeNOK9QkSuiDZ

      # - step:
      #     name: Deploy to Development
      #     deployment: Test
      #     trigger: automatic
      #     clone:
      #       enabled: false
      #     script:
      #       # sync your files to S3
      #       - pipe: atlassian/aws-s3-deploy:1.1.0
      #         variables:
      #           AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      #           AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
      #           AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
      #           S3_BUCKET: 'tune.deploy.bucket'
      #           LOCAL_PATH: 'deploy'
      #           EXTRA_ARGS: '--delete'
